Add chain 369
ethereum/sourcify pull request #1038
Opened 2023-05-22 06:36 UTC by bretep

2023-05-22 06:42 UTC, bretep commented
This line had to be commented out for the test to pass locally. 
https://github.com/ethereum/sourcify/blob/4c396fcf2f3c495760045a8d1da57740cb7ca8c0/test/chains/chain-tests.js#L65

I did not leave it commented out because it was not my addition. :)

2023-05-22 07:42 UTC, kuzdogan requested changes

2023-05-22 07:43 UTC, kuzdogan commented
> This line had to be commented out for the test to pass locally.
> 
> https://github.com/ethereum/sourcify/blob/4c396fcf2f3c495760045a8d1da57740cb7ca8c0/test/chains/chain-tests.js#L65
> 
> I did not leave it commented out because it was not my addition. :)
> 
> It appears that this commit was made when updating all the tests.
> 
> [5e2bd78](https://github.com/ethereum/sourcify/commit/5e2bd780c2b348cf4769917b0e2b192964c54485)

Good catch thank you

2023-08-01 12:28 UTC, kuzdogan commented
Closing due to inactivity.

2023-08-01 12:28 UTC, closed without merging