add new chain for 22776
ethereum/sourcify pull request #1106
Opened 2023-07-12 12:58 UTC by mapdev33

# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request.

## Checklist

- [ ] The branch is named as `add-chain-<chainId>`.
- [ ] I haven't modified the [chains.json](../../src/chains.json) file directly.
- [ ] In [sourcify-chains.ts](../../src/sourcify-chains.ts) file
  - [ ] I've set `supported: true`.
  - [ ] I've set `monitored: false`.
  - [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [ ] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [ ] `test-new-chain` test in Circle CI is passing.

2023-07-13 10:11 UTC, marcocastignoli requested changes

2023-07-13 10:11 UTC, marcocastignoli commented on src/sourcify-chains.ts
> +          ? -1
can you remove these formattings?

2023-07-13 10:11 UTC, marcocastignoli commented on test/chains/chain-tests.js
> +        newAddedChainId +
also these?

2023-07-16 15:13 UTC, kuzdogan commented
The other chain PR created a conflict. Can you please rebase/merge from staging?

2023-07-17 01:40 UTC, closed without merging