Oasis chains: Use new `fetchContractCreationTxUsing` URLs
ethereum/sourcify pull request #1282
Opened 2024-02-28 00:42 UTC by mitjat

# Update Chains 42261, 42262, 23294, 23295

Our Blockchain-compatible explorers are being migrated to new URLs/hostnames. This PR encodes the new hostnames.

## Checklist

- [ ] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've ~added~ a test in [chain-tests.js](../../test/chains/chains-test.js) file. (The old ones still exist.)
- [ ] `test-new-chain` test in Circle CI is passing.

2024-02-28 10:29 UTC, marcocastignoli requested changes

2024-02-28 10:29 UTC, marcocastignoli commented on services/server/src/sourcify-chains-default.json
> +        "url": "https://testnet.old-explorer.sapphire.oasis.dev/"
This one is not working

2024-02-28 19:34 UTC, mitjat commented on services/server/src/sourcify-chains-default.json
> +        "url": "https://testnet.old-explorer.sapphire.oasis.dev/"
Apologies, fixed!

2024-02-29 08:13 UTC, marcocastignoli approved these changes

2024-03-04 19:13 UTC, mitjat commented
Hi @marcocastignoli , is there anything I can do to help merge this? Even if it's just to merge `staging` periodically into this branch.

2024-03-06 08:29 UTC, merged