Split server tests into multiple test files
ethereum/sourcify pull request #1403
Opened 2024-05-22 09:23 UTC by manuelwedler

See #1357 

The biggest improvement of this PR are the `ServerFixture` and `LocalChainFixture` that allow to spin up a server and a local chain for testing. They can be created inside a `describe` block in order to not have one shared server for all tests. In the future we can tweak the options of the fixtures to provide configurations as they are required by specific tests.

Other than that, I created two separate folders inside `test`. One for unit and one for integration tests, since there were also a few unit tests in the server.js file. Overall, this should provide the right structure to keep the tests maintainable in the future when we add more tests.

2024-05-30 14:58 UTC, kuzdogan requested changes
Small thing and a question. Otherwise LGTM

2024-05-30 14:58 UTC, kuzdogan commented on services/server/package.json
> +    "test": "npm run test:unit && npm run test:integration",
Why did we separate it as :unit and :integration? Just for a way to separate tests or for some technical reason?

2024-05-31 13:53 UTC, manuelwedler commented on services/server/test/integration/verification-handlers/verify.session.spec.ts
> +      const metadataPath = path.join(
Looks like it was like this before. But should be changed of course

2024-05-31 14:20 UTC, manuelwedler commented on services/server/test/integration/verification-handlers/verify.session.spec.ts
> +      const metadataPath = path.join(
These two tests were actually never working correctly... just fixed them

2024-06-03 09:48 UTC, kuzdogan approved these changes

2024-06-03 10:24 UTC, merged