Fix bytecode hash calculation by updating variable names
ethereum/sourcify pull request #1414
Opened 2024-05-30 15:41 UTC by marcocastignoli

This PR fixes the bytecode hash calculation, previously inverted.

This PR also:
- adds tests to verify consistency of code.code_hash
- prepares database with new tables and triggers for 'inverted-code-hashes’ fix process.

2024-06-05 14:20 UTC, manuelwedler requested changes
Mainly some improvement to the testing and clarification regarding the second database service.

2024-06-05 14:40 UTC, marcocastignoli commented on services/server/src/server/services/StorageService.ts
> +      this.sourcifyFixedDatabase = new SourcifyDatabaseService(
No because the server should keep using the current database as source of truth until the new database is ready

2024-06-05 14:41 UTC, manuelwedler commented on services/server/src/server/services/StorageService.ts
> +      this.sourcifyFixedDatabase = new SourcifyDatabaseService(
okay makes sense then :+1:

2024-06-06 15:17 UTC, manuelwedler approved these changes
Looks good :)

2024-06-06 15:19 UTC, marcocastignoli commented
I'm going to create a new PR based on this to fix #1419. 

Also, let's wait to merge this until we release.

2024-06-12 00:14 UTC, fantastilicious88 approved these changes

2024-06-13 11:29 UTC, BlackLeopardA2 approved these changes

2024-06-17 09:59 UTC, merged

2024-06-20 22:01 UTC, fantastilicious88 reviewed
Top

2024-06-20 22:02 UTC, fantastilicious88 commented on services/server/test/integration/database.spec.ts
>      // For now disable the creation tests
Top

2024-07-01 03:14 UTC, fantastilicious88 reviewed
Cool