add-chain-16180-62831
ethereum/sourcify pull request #1474
Opened 2024-07-15 14:54 UTC by lolieatapple

# Add New Chain 16180, 62831

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [x] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

2024-07-16 02:17 UTC, Karim8090 approved these changes

2024-07-16 02:18 UTC, Karim8090 approved these changes

2024-07-16 02:39 UTC, Karim8090 commented
heya

2024-07-16 02:39 UTC, Karim8090 approved these changes

2024-07-16 07:52 UTC, manuelwedler requested changes
Hey! Thanks for the PR. The CI fails because the formatting is incorrect. Could you please run `npm run fix` inside `services/server`?

2024-07-16 08:09 UTC, Karim8090 approved these changes

2024-07-17 02:23 UTC, lolieatapple commented
> Hey! Thanks for the PR. The CI fails because the formatting is incorrect. Could you please run `npm run fix` inside `services/server`?

Ok, done.

2024-07-17 09:06 UTC, merged