Oasis chains: add Nexus API fetcher
ethereum/sourcify pull request #1485
Opened 2024-07-18 19:30 UTC by pro-wh

# Update Chains 42261, 42262, 23294, 23295

Oasis chains, namely Sapphire and Emerald are migrating from blockscout to a new explorer backend called Nexus. This adds support for Nexus's API URLs and switches the chain definition to use that.

Oasis Sapphire and Oasis Emerald are "runtimes" (sometimes referred to as ParaTimes in marketing materials) on the Oasis network, so the runtime name is specified as part of the API configuration.

The Oasis Protocol Foundation runs official installations of Nexus at https://nexus.oasis.io (mainnet) and https://testnet.nexus.oasis.io (testnet).

2024-07-18 19:31 UTC, pro-wh commented
tested for regressions with a script like this

services/server/test/chains/get-creator-tests.spec.ts:

```ts
import chai from "chai";
import { getCreatorTx } from "../../src/server/services/utils/contract-creation-util";
import { supportedChainsMap } from "../../src/sourcify-chains";

describe("Test Supported Explorers", function () {
  it("should get creator tx for Ethereum Mainnet", async function () {
    const creator = await getCreatorTx(supportedChainsMap["1"], "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2");
    chai.expect(creator).to.equal('0xb95343413e459a0f97461812111254163ae53467855c0d73e0f1e7c5b8442fa3');
  });
  it("should get creator tx for Oasis Sapphire Mainnet", async function () {
    const creator = await getCreatorTx(supportedChainsMap["23294"], "0x8Bc2B030b299964eEfb5e1e0b36991352E56D2D3");
    chai.expect(creator).to.equal('0xce775b521cc6e1341020560441d77cd634b0972fc34bf96f79e9fab81caa8ab7');
  });
});
```

2024-07-23 14:56 UTC, manuelwedler requested changes
Hey! thanks for the PR. The changes look good to me. Could you please just add these tests in the PR? We have a test file for the contract creation util: `services/server/test/unit/utils/contract-creation-util.spec.ts`

2024-07-23 16:08 UTC, pro-wh commented
:see_no_evil: I missed that file

adding that test :+1:

2024-07-23 16:54 UTC, Chator1 commented
0xFD689e5f2d8d9Aec0aD328225Ae62FdBDdb30328
Abdulhafez 
bdalhafzslah382@gmail.com 
HQ1GIXTTAIZV369C98P8NN4ZH9583NTTYD

2024-07-23 17:32 UTC, pro-wh commented
```
sourcify-server: 2024-07-23T16:10:11.733Z [debug] [Server] Fetched Creator Tx - fetcher={"type":"api","url":"https://api.etherscan.io/api?module=contract&action=getcontractcreation&contractaddresses=${ADDRESS}&apikey="} | contractFetchAddressFilled=https://api.etherscan.io/api?module=contract&action=getcontractcreation&contractaddresses=0x00000000219ab540356cBB839Cbe05303d7705Fa&apikey= | contractAddress=0x00000000219ab540356cBB839Cbe05303d7705Fa | creatorTx=undefined
sourcify-server:     1) should run getCreatorTx with etherscanApi for Etherscan
```

this PR from a fork runs without the API key, so the etherscan test fails. how did the previous run pass though?

2024-07-24 09:02 UTC, manuelwedler commented
Hm I wonder myself why it was running fine before. I think we should skip that test in PRs. Since your test runs fine, we can merge this PR :+1:

2024-07-24 09:02 UTC, manuelwedler approved these changes

2024-07-24 09:02 UTC, merged