Add new chain 7171 & 7771
ethereum/sourcify pull request #1729
Opened 2024-10-29 17:12 UTC by BitrockChain

# Add New Chain <chainId>

Thanks for your pull request to add a new support in Sourcify.

If you haven't done so, please follow the instructions on [how to request chain support](https://docs.sourcify.dev/docs/chain-support/) in docs.

Please check the following items before submitting your pull request for a speedy review.

## Checklist

- [x] The branch is named as `add-chain-<chainId>`.
- [x] I haven't modified the `chains.json` file directly.
- [x] In `sourcify-chains.json` file
  - [x] I've set `supported: true`.
  - [ ] I haven't added an `rpc` field but the one in [chains.json](../../src/chains.json) is used (if not, please explain why).
- [x] I've added a test in [chain-tests.js](../../test/chains/chains-test.js) file.
- [x] `test-new-chain` test in Circle CI is passing.

2024-11-01 09:43 UTC, manuelwedler commented
Thanks for the PR. We still need to fix our tests ([#1734](https://github.com/ethereum/sourcify/issues/1734)), before we can merge this.

2024-11-01 09:47 UTC, manuelwedler requested changes
What I can tell already is that you can remove the rpc fields, because the RPCs are already inside chains.json

2024-11-01 09:47 UTC, manuelwedler commented on services/server/src/sourcify-chains-default.json
> +    "rpc": ["https://testnet.bit-rock.io/"]
Please remove this

2024-11-01 09:47 UTC, manuelwedler commented on services/server/src/sourcify-chains-default.json
> +    "rpc": ["https://brockrpc.io/"]
Please remove this

2024-11-01 09:52 UTC, BitrockChain commented
Removed, thanks @manuelwedler

2024-11-01 10:50 UTC, BitrockChain commented
> Thanks for the PR. We still need to fix our tests ([#1734](https://github.com/ethereum/sourcify/issues/1734)), before we can merge this.

Thanks, You’re the best!

2024-11-04 11:11 UTC, manuelwedler commented
Your last commit removed the configuration changes completely. I added it again

2024-11-04 11:59 UTC, manuelwedler approved these changes

2024-11-04 11:59 UTC, merged

2024-11-04 12:02 UTC, BitrockChain commented
hi @manuelwedler thanks for merged.

2025-12-30 14:01 UTC, manuelwedler commented
@BitrockChain I'm disabling this chain as it has been constantly failing in our CI. Please reach out in case you still want to be supported by Sourcify. https://github.com/argotorg/sourcify/pull/2557