Refactor UI for shared SerchSelect,init json endp.
ethereum/sourcify pull request #980
Opened 2023-04-17 10:41 UTC by kuzdogan

Refactor SearchSelect's onChange function and its types to be able to reuse SearchSelect consistently.

Initial naive implementation of using solcJson as input in session

2023-04-24 14:01 UTC, marcocastignoli requested changes
Just two small things, great job! 🚀

2023-04-25 16:23 UTC, kuzdogan commented on src/server/controllers/VerificationController.ts
> +  private addInputSolcJsonEndpoint = async (req: Request, res: Response) => {
It's not actually a "verify" endpoint so I'd refrain from that.

Also other "file/contract add" endpoints are named similarly, that's why I named it that way
<img width="609" alt="image" src="https://user-images.githubusercontent.com/13069972/234340820-3d2bcdb2-eff3-4feb-a421-bcbf08c7c359.png">

So either:
- Change all other endpoint names
- Keep all the same

2023-04-26 04:18 UTC, haltman-at commented
Question from an interested outsider: What would happen if someone used this interface to attempt to verify a Yul contract, setting `"language": "Yul"` rather than `"language": "Solidity"`?

2023-04-26 08:55 UTC, kuzdogan commented
@haltman-at Thanks for pointing this out! 

I tried with the examples in the Solidity docs [Yul page](https://docs.soliditylang.org/en/latest/yul.html#complete-erc20-example). The compiler compiles just fine but since the compiler output JSON does not have `.contracts`, no source code and metadata file get added to the session.

So we should check if the language is "Solidity"

2023-04-26 13:44 UTC, marcocastignoli approved these changes

2023-04-26 13:47 UTC, merged